package main

import "google.golang.org/protobuf/compiler/protogen"

func generateServer(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_go-scrpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-scrpc. DO NOT EDIT.")
	g.P("// path ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}
